# Generated by Django 3.1.6 on 2021-02-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('exercise_type', models.CharField(default='accessory', max_length=100)),
                ('movement_type', models.CharField(default='none', max_length=100)),
                ('exercise_PR_increment', models.CharField(max_length=100)),
                ('recovery', models.CharField(default='1', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('health_date', models.CharField(default='health_2021_02_14', max_length=100)),
                ('supplements_date', models.CharField(default='supplements_2021_02_14', max_length=100)),
                ('primary_lift_date', models.CharField(default='primary_lift_2021_02_14', max_length=100)),
                ('assistance_lift_1_date', models.CharField(default='assistance_lift_1_2021_02_14', max_length=100)),
                ('assistance_lift_2_date', models.CharField(default='assistance_lift_2_2021_02_14', max_length=100)),
                ('accessory_lift_1_date', models.CharField(default='accessory_lift_1_2021_02_14', max_length=100)),
                ('accessory_ift_2_date', models.CharField(default='accessory_lift_2_2021_02_14', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatine', models.CharField(max_length=10)),
                ('caffeine', models.CharField(max_length=10)),
                ('multivitamin', models.CharField(max_length=10)),
                ('magnesium', models.CharField(max_length=10)),
                ('cbd_oil', models.CharField(max_length=10)),
                ('fish_oil', models.CharField(max_length=10)),
                ('b_complex', models.CharField(max_length=10)),
                ('b12', models.CharField(max_length=10)),
                ('ashwaghanda', models.CharField(max_length=10)),
                ('zinc', models.CharField(max_length=10)),
                ('vitamin_c', models.CharField(max_length=10)),
                ('vitamin_d3', models.CharField(max_length=10)),
                ('lemon_balm', models.CharField(max_length=10)),
                ('supplements_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workout')),
            ],
            options={
                'verbose_name_plural': 'Supplements',
            },
        ),
        migrations.CreateModel(
            name='Primary_Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_exercise', models.CharField(max_length=10)),
                ('primary_equipment', models.ImageField(upload_to='equipment/')),
                ('primary_weight', models.CharField(max_length=10)),
                ('primary_reps', models.CharField(max_length=10)),
                ('primary_rest', models.CharField(max_length=10)),
                ('primary_difficulty', models.CharField(max_length=10)),
                ('primary_notes', models.CharField(max_length=100)),
                ('primary_lift_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workouts')),
            ],
            options={
                'verbose_name_plural': 'Primary_Lifts',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning_weight', models.CharField(max_length=10)),
                ('morning_waist', models.CharField(max_length=10)),
                ('hrv', models.CharField(max_length=10)),
                ('readiness', models.CharField(max_length=10)),
                ('sleep', models.CharField(max_length=10)),
                ('calories', models.CharField(max_length=10)),
                ('mood_night', models.CharField(max_length=10)),
                ('water_night', models.CharField(max_length=10)),
                ('health_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workout')),
            ],
            options={
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Assistance_Lift_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_exercise_2', models.CharField(max_length=10)),
                ('assistance_equipment_2', models.ImageField(upload_to='equipment/')),
                ('assistance_weight_2_set_1', models.CharField(max_length=10)),
                ('assistance_reps_2_set_1', models.CharField(max_length=10)),
                ('assistance_weight_2_set_2', models.CharField(max_length=10)),
                ('assistance_reps_2_set_2', models.CharField(max_length=10)),
                ('assistance_weight_2_set_3', models.CharField(max_length=10)),
                ('assistance_reps_2_set_3', models.CharField(max_length=10)),
                ('assistance_2_rest', models.CharField(max_length=10)),
                ('assistance_2_difficulty', models.CharField(max_length=10)),
                ('assistance_2_notes', models.CharField(max_length=100)),
                ('assistance_2_lift_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workouts')),
            ],
            options={
                'verbose_name_plural': 'Assistance_2_Lifts',
            },
        ),
        migrations.CreateModel(
            name='Assistance_Lift_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_exercise_1', models.CharField(max_length=10)),
                ('assistance_equipment_1', models.ImageField(upload_to='equipment/')),
                ('assistance_weight_1_set_1', models.CharField(max_length=10)),
                ('assistance_reps_1_set_1', models.CharField(max_length=10)),
                ('assistance_weight_1_set_2', models.CharField(max_length=10)),
                ('assistance_reps_1_set_2', models.CharField(max_length=10)),
                ('assistance_weight_1_set_3', models.CharField(max_length=10)),
                ('assistance_reps_1_set_3', models.CharField(max_length=10)),
                ('assistance_1_rest', models.CharField(max_length=10)),
                ('assistance_1_difficulty', models.CharField(max_length=10)),
                ('assistance_1_notes', models.CharField(max_length=100)),
                ('assistance_1_lift_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workouts')),
            ],
            options={
                'verbose_name_plural': 'Assistance_1_Lifts',
            },
        ),
        migrations.CreateModel(
            name='Accessory_Lift_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_exercise_2', models.CharField(max_length=10)),
                ('accessory_equipment_2', models.ImageField(upload_to='equipment/')),
                ('accessory_weight_2_set_1', models.CharField(max_length=10)),
                ('accessory_reps_2_set_1', models.CharField(max_length=10)),
                ('accessory_weight_2_set_2', models.CharField(max_length=10)),
                ('accessory_reps_2_set_2', models.CharField(max_length=10)),
                ('accessory_weight_2_set_3', models.CharField(max_length=10)),
                ('accessory_reps_2_set_3', models.CharField(max_length=10)),
                ('accessory_2_rest', models.CharField(max_length=10)),
                ('accessory_2_difficulty', models.CharField(max_length=10)),
                ('accessory_2_notes', models.CharField(max_length=100)),
                ('accessory_2_lift_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workouts')),
            ],
            options={
                'verbose_name_plural': 'Accessory_2_Lifts',
            },
        ),
        migrations.CreateModel(
            name='Accessory_Lift_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_exercise_1', models.CharField(max_length=10)),
                ('accessory_equipment_1', models.ImageField(upload_to='equipment/')),
                ('accessory_weight_1_set_1', models.CharField(max_length=10)),
                ('accessory_reps_1_set_1', models.CharField(max_length=10)),
                ('accessory_weight_1_set_2', models.CharField(max_length=10)),
                ('accessory_reps_1_set_2', models.CharField(max_length=10)),
                ('accessory_weight_1_set_3', models.CharField(max_length=10)),
                ('accessory_reps_1_set_3', models.CharField(max_length=10)),
                ('accessory_1_rest', models.CharField(max_length=10)),
                ('accessory_1_difficulty', models.CharField(max_length=10)),
                ('accessory_1_notes', models.CharField(max_length=100)),
                ('accessory_1_lift_date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ronboutilier.workout', verbose_name='Workouts')),
            ],
            options={
                'verbose_name_plural': 'Accessory_1_Lifts',
            },
        ),
    ]
