# Generated by Django 3.1.6 on 2021-02-14 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ronboutilier', '0002_auto_20210214_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='Lifter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
