# Generated by Django 3.1.6 on 2021-02-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ronboutilier', '0003_workout_lifter'),
    ]


    operations = [
        migrations.RunSQL("""
            INSERT INTO ronboutilier_Exercises (
                exercise_name,
                exercise_type,
                movement_type,
		exercise_PR_increment,
		recovery
            )
            SELECT
                exercise_name,
		exercise_type,
		movement_type,
                exercise_PR_increment,
                recovery
            FROM
                steamroller_Exercise;
        """, reverse_sql="""
            INSERT INTO steamroller_Exercise (
                exercise_name,
		exercise_type,
		movement_type,
                exercise_PR_increment,
                recovery
            )
            SELECT
                exercise_name,
		exercise_type,
		movement_type,
                exercise_PR_increment,
                recovery
            FROM
                ronboutilier_Exercises;
        """)
    ]
