# Generated by Django 3.1.6 on 2021-02-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronboutilier', '0004_auto_20210214_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory_lift_2',
            old_name='primary_exercise_2',
            new_name='accessory_exercise_2',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='supplements_date',
        ),
        migrations.AlterField(
            model_name='workout',
            name='accessory_ift_2_date',
            field=models.CharField(default='accessory_lift_2_2021_02_16', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='accessory_lift_1_date',
            field=models.CharField(default='accessory_lift_1_2021_02_16', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='assistance_lift_1_date',
            field=models.CharField(default='assistance_lift_1_2021_02_16', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='assistance_lift_2_date',
            field=models.CharField(default='assistance_lift_2_2021_02_16', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='health_date',
            field=models.CharField(default='health_2021_02_16', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='primary_lift_date',
            field=models.CharField(default='primary_lift_2021_02_16', max_length=100),
        ),
        migrations.DeleteModel(
            name='Supplements',
        ),
    ]
