# Generated by Django 3.0.3 on 2020-08-08 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.CharField(max_length=200)),
                ('bridge_summary', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Bridge',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('trip_summary', models.CharField(max_length=200)),
                ('trip_slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.CharField(max_length=200)),
                ('element_notes', models.TextField()),
                ('element_published', models.DateTimeField(default=datetime.datetime(2020, 8, 8, 13, 57, 32, 936594), verbose_name='date published')),
                ('element_slug', models.CharField(default=1, max_length=200)),
                ('bridge_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Bridge', verbose_name='Bridge')),
            ],
        ),
        migrations.AddField(
            model_name='bridge',
            name='trip_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Trip', verbose_name='Trip'),
        ),
    ]
