# Generated by Django 3.0.3 on 2020-08-24 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200823_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AlterField(
            model_name='element',
            name='element_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 12, 21, 53, 632952), verbose_name='date published'),
        ),
    ]
