# Generated by Django 3.0.3 on 2020-08-24 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200824_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 16, 50, 622394), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.CharField(max_length=100)),
                ('selection_set', models.FileField(upload_to='trips/')),
                ('inspector', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
