# Generated by Django 3.0.3 on 2020-08-25 00:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200824_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='inspector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='selection_set',
            field=models.FileField(default=1, upload_to='trips/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='element_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 16, 57, 0, 436170), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
