# Generated by Django 3.0.3 on 2020-08-25 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200824_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_slug',
        ),
        migrations.AlterField(
            model_name='element',
            name='element_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 20, 1, 37, 870163), verbose_name='date published'),
        ),
    ]
