# Generated by Django 3.0.3 on 2021-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201024_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='bridge_status',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='notes',
            name='trip_notes',
            field=models.CharField(default='add trip details here', max_length=200),
        ),
    ]
