# Generated by Django 3.0.3 on 2021-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210109_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='bridge_status',
        ),
        migrations.AddField(
            model_name='notes',
            name='inspected',
            field=models.CharField(default='   ', max_length=3),
        ),
    ]
