# Generated by Django 3.0.3 on 2021-01-16 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_bridge_status_inspected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.CharField(max_length=200)),
                ('inspected', models.BooleanField(default=False)),
                ('initials', models.CharField(max_length=200)),
                ('trip_notes', models.CharField(max_length=200)),
                ('element_notes', models.FileField(upload_to='notes/')),
                ('element_history', models.FileField(upload_to='history/')),
                ('trip_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Selection_Sets', verbose_name='Set')),
            ],
            options={
                'verbose_name_plural': 'Bridge',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=200)),
                ('photos', models.ImageField(upload_to='photos/')),
                ('structure_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Bridge', verbose_name='Bridge')),
            ],
            options={
                'verbose_name_plural': 'Element',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='history',
            name='trip_name',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='trip_name',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='structure_id',
        ),
        migrations.RemoveField(
            model_name='trip_notes',
            name='trip_name',
        ),
        migrations.DeleteModel(
            name='Bridge_Status',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Trip_Notes',
        ),
    ]
