# Generated by Django 3.0.3 on 2021-01-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210116_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='initials',
            field=models.CharField(max_length=3),
        ),
    ]
