# Generated by Django 3.0.3 on 2021-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210116_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='trip_notes',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
