# Generated by Django 3.0.3 on 2021-01-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210117_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='trip_notes',
            field=models.CharField(default='enter details here', max_length=200),
        ),
    ]
