# Generated by Django 3.1.5 on 2021-02-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210117_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='trip_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.selection_sets', verbose_name='Set'),
        ),
        migrations.AlterField(
            model_name='element',
            name='structure_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.bridge', verbose_name='Bridge'),
        ),
    ]
