# Generated by Django 3.1.6 on 2021-02-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210206_0359'),
        ('main', '0023_auto_20210206_0335'),
    ]

    operations = [
    ]
