# Generated by Django 3.1.6 on 2021-02-09 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_merge_20210207_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection_sets',
            name='co',
            field=models.CharField(default='xxx', max_length=3),
        ),
        migrations.AddField(
            model_name='selection_sets',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='selection_sets',
            name='lead',
            field=models.CharField(default='xxx', max_length=3),
        ),
        migrations.AddField(
            model_name='selection_sets',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
