# Generated by Django 3.1.6 on 2021-02-13 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0002_remove_workout_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='exercise_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='steamroller.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='muscle_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='steamroller.muscle', verbose_name='Muscle'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='muscle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='accessory_ift_2_date',
            field=models.CharField(default='accessory_lift_2_2021_02_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='accessory_lift_1_date',
            field=models.CharField(default='accessory_lift_1_2021_02_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='assistance_lift_1_date',
            field=models.CharField(default='assistance_lift_1_2021_02_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='assistance_lift_2_date',
            field=models.CharField(default='assistance_lift_2_2021_02_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='health_date',
            field=models.CharField(default='health_2021_02_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='primary_lift_date',
            field=models.CharField(default='primary_lift_2021_02_13', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='supplements_date',
            field=models.CharField(default='supplements_2021_02_13', max_length=100),
        ),
    ]
