# Generated by Django 3.1.6 on 2021-02-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0004_exercise_exercise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
    ]
