# Generated by Django 3.1.6 on 2021-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0005_remove_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(default='accessory', max_length=100),
        ),
    ]
