# Generated by Django 3.1.6 on 2021-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0006_auto_20210213_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(default='accessory', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=100),
        ),
    ]
