# Generated by Django 3.1.6 on 2021-02-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0007_auto_20210213_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscle',
            name='muscle_atrophy',
        ),
    ]
