# Generated by Django 3.1.6 on 2021-02-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0008_remove_muscle_muscle_atrophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='recovery',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.DeleteModel(
            name='Combination',
        ),
        migrations.DeleteModel(
            name='Muscle',
        ),
    ]
