# Generated by Django 3.1.6 on 2021-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamroller', '0009_auto_20210213_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='accessory_ift_2_date',
            field=models.CharField(default='accessory_lift_2_2021_02_14', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='accessory_lift_1_date',
            field=models.CharField(default='accessory_lift_1_2021_02_14', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='assistance_lift_1_date',
            field=models.CharField(default='assistance_lift_1_2021_02_14', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='assistance_lift_2_date',
            field=models.CharField(default='assistance_lift_2_2021_02_14', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='health_date',
            field=models.CharField(default='health_2021_02_14', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='primary_lift_date',
            field=models.CharField(default='primary_lift_2021_02_14', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='supplements_date',
            field=models.CharField(default='supplements_2021_02_14', max_length=100),
        ),
    ]
