# Generated by Django 3.1.6 on 2021-02-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steamroller', '0010_auto_20210214_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='Lifter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
